import { KResource } from '../model';

export const mockKResourcesData: KResource[] = [
  {
    country_code: 'KR',
    resource_id: 1,
    resource_name: 'BTS',
    type: 'Group',
    status: 'Active',
    tags: ['RM', '진', '슈가', '제이홉', '지민', '뷔', '정국'],
    partner: 'SM 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 2,
    resource_name: 'BLACKPINK',
    type: 'Group',
    status: 'Active',
    tags: ['지수', '제니', '로제', '리사'],
    partner: 'YG 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 3,
    resource_name: 'TWICE',
    type: 'Group',
    status: 'Active',
    tags: ['나연', '정연', '모모', '사나', '지효', '미나', '다현', '채영', '쯔위'],
    partner: 'JYP 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 4,
    resource_name: 'EXO',
    type: 'Group',
    status: 'Active',
    tags: ['수호', '시우민', '레이', '백현', '첸', '찬열', '디오', '카이', '세훈'],
    partner: 'SM 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 5,
    resource_name: 'Red Velvet',
    type: 'Group',
    status: 'Active',
    tags: ['아이린', '슬기', '웬디', '조이', '예리'],
    partner: 'SM 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 6,
    resource_name: 'SEVENTEEN',
    type: 'Group',
    status: 'Active',
    tags: ['에스쿱스', '정한', '조슈아', '준', '호시', '원우', '우지', '디에잇', '민규', '도겸', '승관', '버논', '디노'],
    partner: 'SM 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 7,
    resource_name: 'ITZY',
    type: 'Group',
    status: 'Active',
    tags: ['예지', '리아', '류진', '채령', '유나'],
    partner: 'SM 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 8,
    resource_name: 'NCT 127',
    type: 'Group',
    status: 'Active',
    tags: ['태일', '쟈니', '태용', '유타', '도영', '재현', '정우', '마크', '해찬'],
    partner: 'SM 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 9,
    resource_name: 'LE SSERAFIM',
    type: 'Group',
    status: 'Active',
    tags: ['사쿠라', '김채원', '허윤진', '카즈하', '홍은채'],
    partner: 'SM 엔터테인먼트',
  },
  {
    country_code: 'KR',
    resource_id: 10,
    resource_name: 'Stray Kids',
    type: 'Group',
    status: 'Active',
    tags: ['방찬', '리노', '창빈', '현진', '한', '필릭스', '승민', '아이엔'],
    partner: 'JYP 엔터테인먼트',
  },
];
