import { PendingPartners } from '../model';

export const initialPendingPartners: PendingPartners[] = [
  {
    id: '1',
    company_name: 'SM엔터테인먼트',
    account_type: '파트너',
    grade: '브론즈',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '2',
    company_name: 'JYP엔터테인먼트',
    account_type: '파트너',
    grade: '실버',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '3',
    company_name: 'YG엔터테인먼트',
    account_type: '파트너',
    grade: '골드',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '4',
    company_name: '빅히트엔터테인먼트',
    account_type: '파트너',
    grade: '다이아',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '5',
    company_name: '미미랩',
    account_type: '파트너',
    grade: '플래티넘',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '6',
    company_name: '미미랩',
    account_type: '파트너',
    grade: '크리스탈',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '7',
    company_name: '미미랩',
    account_type: '파트너',
    grade: '마스터',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '8',
    company_name: '미미랩',
    account_type: '파트너',
    grade: '그랜드 마스터',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '9',
    company_name: '미미랩',
    account_type: '파트너',
    grade: '챌린저',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '10',
    company_name: '미미랩',
    account_type: '파트너',
    grade: '프로',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
  {
    id: '11',
    company_name: '미미랩',
    account_type: '파트너',
    grade: '베이직',
    request_at: '2025-07-09',
    primary_contact_name: '김민준',
  },
];
