import { AdminUser } from '../model';

export const adminData: AdminUser[] = [
  {
    id: 'ADM001',
    name: 'John Smith',
    role: 'Admin',
    signup_date: '2023-01-15',
    status: 'Active',
  },
  {
    id: 'ADM002',
    name: 'Sarah Johnson',
    role: 'Member',
    signup_date: '2023-03-22',
    status: 'Active',
  },
  {
    id: 'ADM003',
    name: 'Michael Brown',
    role: 'Member',
    signup_date: '2023-05-10',
    status: 'InActive',
  },
  {
    id: 'ADM004',
    name: 'Emily Davis',
    role: 'Admin',
    signup_date: '2023-07-08',
    status: 'Active',
  },
  {
    id: 'ADM005',
    name: 'David Wilson',
    role: 'Member',
    signup_date: '2023-09-12',
    status: 'InActive',
  },
  {
    id: 'ADM006',
    name: 'Lisa Anderson',
    role: 'Admin',
    signup_date: '2023-11-05',
    status: 'Active',
  },
  {
    id: 'ADM007',
    name: 'Robert Taylor',
    role: 'Member',
    signup_date: '2023-12-18',
    status: 'Active',
  },
  {
    id: 'ADM008',
    name: 'Jennifer Martinez',
    role: 'Admin',
    signup_date: '2024-01-03',
    status: 'Active',
  },
  {
    id: 'ADM009',
    name: 'Christopher Lee',
    role: 'Member',
    signup_date: '2024-01-08',
    status: 'InActive',
  },
  {
    id: 'ADM010',
    name: 'Amanda Garcia',
    role: 'Admin',
    signup_date: '2024-01-12',
    status: 'Active',
  },
  {
    id: 'ADM011',
    name: 'Rajesh Kumar',
    role: 'Admin',
    signup_date: '2024-05-12',
    status: 'InActive',
  },
];
